# Suite à issue19402, on vérifie :
#   - que l'objet aster.error est présent dans le pick.1,
#   - et qu'on peut donc poursuivre le calcul.
POURSUITE(CODE=_F(NOM='ERREU09A'),
          PAR_LOT='OUI',);

is_ok = int(isinstance(err, aster.error))

TAB1=CREA_TABLE(LISTE=(_F(PARA='TEST',TYPE_K='K8',LISTE_K='VALEUR  ',),
                       _F(PARA='BOOLEEN',LISTE_I=is_ok,),
                       ),
                )
TEST_TABLE(REFERENCE='ANALYTIQUE',
           VALE_CALC_I=1,
           VALE_REFE_I=1,
           NOM_PARA='BOOLEEN',
           TABLE=TAB1,
           FILTRE=_F(NOM_PARA='TEST',
                     VALE_K='VALEUR  ',),
           )

FIN()
